# NumPy / Linear Algebra Dimensional Overview

* 0D → scalar
    * A single number
    * Shape: ()

* 1D → 1D array (conceptually a vector) 🤯
    * Sequence of numbers, no explicit row/column orientation
    * Shape: (n,) — e.g., (5,)

* 2D → matrix (rows × columns)
    * Standard 2D array
    * Shape: (m, n)

        * (1, n) → row vector
        * (m, 1) → column vector

* 3D and higher → tensor

    * Multi-dimensional array
    * Shape: (k, l, m) or more axes
        * Example: images (height, width, channels) or batches (batch_size, H, W, C)

In [35]:
import numpy as np

zeroD = np.array(3)  # 0D array
print('shape of 0D: ', zeroD.shape)  # ()

oneD = np.array([2, 3, 4])
print('shape of 1D: ', oneD.shape)  # (3,)


shape of 0D:  ()
shape of 1D:  (3,)


In [36]:
twoD = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print('shape of 2D: ', twoD.shape)  # (2,3)

# Using simple array of 1Ds
twoDbyoneDs = np.array([oneD, oneD, oneD])
print('2D from 1Ds, shape:', twoDbyoneDs.shape, '\n', twoDbyoneDs)

# Using np.stack
twoDbyoneDs_stack = np.stack([oneD, oneD, oneD], axis=0)
print('2D from 1Ds using np.stack, shape:', twoDbyoneDs_stack.shape, '\n', twoDbyoneDs_stack)

# Using np.tile
twoDbyoneDs_tile = np.tile(oneD, (3, 1))
print('2D from 1Ds using np.tile, shape:', twoDbyoneDs_tile.shape, '\n', twoDbyoneDs_tile)

shape of 2D:  (2, 3)
2D from 1Ds, shape: (3, 3) 
 [[2 3 4]
 [2 3 4]
 [2 3 4]]
2D from 1Ds using np.stack, shape: (3, 3) 
 [[2 3 4]
 [2 3 4]
 [2 3 4]]
2D from 1Ds using np.tile, shape: (3, 3) 
 [[2 3 4]
 [2 3 4]
 [2 3 4]]


In [38]:
print('---------------------')
print('Here are tensors\n')

# Original small 3D array
threeD = np.array([
    [[1], [4]],  # first matrix
    [[2], [5]]   # second matrix
])
print('Original 3D array, shape:', threeD.shape)
for i, matrix in enumerate(threeD):
    print(f"Matrix {i}:\n{matrix}\n")

# 3D from 2Ds using different methods
threeDby2Ds = np.array([twoD, twoD, twoD])
print('3D from 2Ds using np.array, shape:', threeDby2Ds.shape)
for i, matrix in enumerate(threeDby2Ds):
    print(f"Matrix {i}:\n{matrix}\n")

threeDby2Ds_stack = np.stack([twoD, twoD, twoD], axis=0)
print('3D from 2Ds using np.stack, shape:', threeDby2Ds_stack.shape)
for i, matrix in enumerate(threeDby2Ds_stack):
    print(f"Matrix {i}:\n{matrix}\n")

threeDby2Ds_tile = np.tile(twoD, (3, 1, 1))
print('3D from 2Ds using np.tile, shape:', threeDby2Ds_tile.shape)
for i, matrix in enumerate(threeDby2Ds_tile):
    print(f"Matrix {i}:\n{matrix}\n")

---------------------
Here are tensors

Original 3D array, shape: (2, 2, 1)
Matrix 0:
[[1]
 [4]]

Matrix 1:
[[2]
 [5]]

3D from 2Ds using np.array, shape: (3, 2, 3)
Matrix 0:
[[1 2 3]
 [4 5 6]]

Matrix 1:
[[1 2 3]
 [4 5 6]]

Matrix 2:
[[1 2 3]
 [4 5 6]]

3D from 2Ds using np.stack, shape: (3, 2, 3)
Matrix 0:
[[1 2 3]
 [4 5 6]]

Matrix 1:
[[1 2 3]
 [4 5 6]]

Matrix 2:
[[1 2 3]
 [4 5 6]]

3D from 2Ds using np.tile, shape: (3, 2, 3)
Matrix 0:
[[1 2 3]
 [4 5 6]]

Matrix 1:
[[1 2 3]
 [4 5 6]]

Matrix 2:
[[1 2 3]
 [4 5 6]]



In [39]:
# ---------------------
# 4D tensor: stack multiple 3D tensors along a new axis
fourD = np.array([threeDby2Ds, threeDby2Ds, threeDby2Ds])  # shape (3, 3, 2, 3)
print('4D tensor from 3D tensors using np.array, shape:', fourD.shape)

# Print clearly: iterate over first two axes
for i, tensor3D in enumerate(fourD):
    print(f"\n3D block {i} (shape {tensor3D.shape}):")
    for j, matrix in enumerate(tensor3D):
        print(f"  Matrix {j}:\n{matrix}")

4D tensor from 3D tensors using np.array, shape: (3, 3, 2, 3)

3D block 0 (shape (3, 2, 3)):
  Matrix 0:
[[1 2 3]
 [4 5 6]]
  Matrix 1:
[[1 2 3]
 [4 5 6]]
  Matrix 2:
[[1 2 3]
 [4 5 6]]

3D block 1 (shape (3, 2, 3)):
  Matrix 0:
[[1 2 3]
 [4 5 6]]
  Matrix 1:
[[1 2 3]
 [4 5 6]]
  Matrix 2:
[[1 2 3]
 [4 5 6]]

3D block 2 (shape (3, 2, 3)):
  Matrix 0:
[[1 2 3]
 [4 5 6]]
  Matrix 1:
[[1 2 3]
 [4 5 6]]
  Matrix 2:
[[1 2 3]
 [4 5 6]]


# Normalization is Ez
## MinMaxScaler
### x′=max(x)−min(x)/x−min(x) is how minmax scaler works

### In NumPy, if you pass -1 as one of the dimensions, it means:
### “figure this dimension out automatically, so that the total number of elements stays the same.”


In [1]:
from sklearn.preprocessing import MinMaxScaler

# Example numpy array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]], dtype=float)

# Initialize MinM   axScaler to scale values into [0, 1]
scaler = MinMaxScaler()

# Fit and transform the array
scaled_arr = scaler.fit_transform(arr)

print("Original array:\n", arr)
print("\nScaled array:\n", scaled_arr)

Original array:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Scaled array:
 [[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


### As it may seem, MinMaxScaler works columnwise

### arr.reshape(1, -1) results in a row vector
### arr_aranaged.reshape(-1, 1) results in a column vector, so this one is used to make a 1D array scaled and then to be used

In [8]:
arr_aranaged = np.arange(100)  # this is not in space
print(arr_aranaged.reshape(1, -1))  # see a row

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
  48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
  72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
  96 97 98 99]]


In [11]:
arr_aranaged_reshaped = arr_aranaged.reshape(1, -1)  # same row
arr_aranaged_scaled = scaler.fit_transform(arr_aranaged_reshaped)
arr_aranaged_scaled  # x′=max(x)−min(x)/x−min(x), indeed here when calculated it results in 0/0 because max(x)=min(x)=x and thereby x-x/x-x but scikit-learn handles it and gives 0

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [16]:
arr_aranaged = np.arange(100)
print(arr_aranaged.reshape(-1, 1))  # see a column now

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]
 [31]
 [32]
 [33]
 [34]
 [35]
 [36]
 [37]
 [38]
 [39]
 [40]
 [41]
 [42]
 [43]
 [44]
 [45]
 [46]
 [47]
 [48]
 [49]
 [50]
 [51]
 [52]
 [53]
 [54]
 [55]
 [56]
 [57]
 [58]
 [59]
 [60]
 [61]
 [62]
 [63]
 [64]
 [65]
 [66]
 [67]
 [68]
 [69]
 [70]
 [71]
 [72]
 [73]
 [74]
 [75]
 [76]
 [77]
 [78]
 [79]
 [80]
 [81]
 [82]
 [83]
 [84]
 [85]
 [86]
 [87]
 [88]
 [89]
 [90]
 [91]
 [92]
 [93]
 [94]
 [95]
 [96]
 [97]
 [98]
 [99]]


In [42]:
arr_aranaged_reshaped = arr_aranaged.reshape(-1, 1)  # the column
arr_aranaged_scaled = scaler.fit_transform(arr_aranaged_reshaped)
print('100 scaled values, shape: ', arr_aranaged_scaled.shape, '\n', 'so a column vector again')
arr_aranaged_scaled  # x′=max(x)−min(x)/x−min(x), indeed here when calculated it results in 0/0 because max(x)=min(x)=x and thereby x-x/x-x but scikit-learn handles it and gives 0

100 scaled values, shape:  (100, 1) 
 so a column vector again


array([[0.        ],
       [0.01010101],
       [0.02020202],
       [0.03030303],
       [0.04040404],
       [0.05050505],
       [0.06060606],
       [0.07070707],
       [0.08080808],
       [0.09090909],
       [0.1010101 ],
       [0.11111111],
       [0.12121212],
       [0.13131313],
       [0.14141414],
       [0.15151515],
       [0.16161616],
       [0.17171717],
       [0.18181818],
       [0.19191919],
       [0.2020202 ],
       [0.21212121],
       [0.22222222],
       [0.23232323],
       [0.24242424],
       [0.25252525],
       [0.26262626],
       [0.27272727],
       [0.28282828],
       [0.29292929],
       [0.3030303 ],
       [0.31313131],
       [0.32323232],
       [0.33333333],
       [0.34343434],
       [0.35353535],
       [0.36363636],
       [0.37373737],
       [0.38383838],
       [0.39393939],
       [0.4040404 ],
       [0.41414141],
       [0.42424242],
       [0.43434343],
       [0.44444444],
       [0.45454545],
       [0.46464646],
       [0.474

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [47]:
as_array_test = np.asarray(twoDbyoneDs)

In [49]:
as_array_test.min(axis=0)

array([2, 3, 4])

In [44]:
import numpy as np

class MyMinMaxScaler:
    def __init__(self, feature_range=(0, 1)):
        self.feature_range = feature_range
        self.data_min_ = None
        self.data_max_ = None
        self.scale_ = None
        self.min_ = None

    def fit(self, X: np.ndarray):
        """
        Learn min and max for each column
        """
        X = np.asarray(X, dtype=float)
        self.data_min_ = X.min(axis=0)
        self.data_max_ = X.max(axis=0)
        data_range = self.data_max_ - self.data_min_

        # Handle columns where max = min
        data_range[data_range == 0] = 1

        self.scale_ = (self.feature_range[1] - self.feature_range[0]) / data_range
        self.min_ = self.feature_range[0] - self.data_min_ * self.scale_
        return self

    def transform(self, X: np.ndarray):
        """
        Scale X using learned min and max
        """
        X = np.asarray(X, dtype=float)
        return X * self.scale_ + self.min_

    def fit_transform(self, X: np.ndarray):
        self.fit(X)
        return self.transform(X)

    def inverse_transform(self, X_scaled: np.ndarray):
        """
        Convert scaled values back to original
        """
        X_scaled = np.asarray(X_scaled, dtype=float)
        return (X_scaled - self.min_) / self.scale_


# ===== Example =====
X = np.array([
    [1, 200, 3],
    [4, 200, 6],
    [7, 200, 9]
])

scaler = MyMinMaxScaler()
X_scaled = scaler.fit_transform(X)
print("Scaled:\n", X_scaled)

# inverse_transform
X_inv = scaler.inverse_transform(X_scaled)
print("\nInverse transformed:\n", X_inv)

Scaled:
 [[0.  0.  0. ]
 [0.5 0.  0.5]
 [1.  0.  1. ]]

Inverse transformed:
 [[  1. 200.   3.]
 [  4. 200.   6.]
 [  7. 200.   9.]]


In [50]:
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)
print("Scaled:\n", X_scaled)

# inverse_transform
X_inv = scaler.inverse_transform(X_scaled)
print("\nInverse transformed:\n", X_inv)

Scaled:
 [[0.  0.  0. ]
 [0.5 0.  0.5]
 [1.  0.  1. ]]

Inverse transformed:
 [[  1. 200.   3.]
 [  4. 200.   6.]
 [  7. 200.   9.]]


# StandartScaler xi'=xi−μ/σ

* xi → original value
* μ → mean of the feature/column
* σ → standard deviation of the feature/column
* xi' → standardized value

After standardization:
* Mean of the feature becomes 0
* Standard deviation becomes 1

Handles each feature independently (column-wise)
If σ=0 (constant column), you typically return 0 to avoid division by zero.

In [51]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("Scaled:\n", X_scaled)

# inverse_transform
X_inv = scaler.inverse_transform(X_scaled)
print("\nInverse transformed:\n", X_inv)

Scaled:
 [[-1.22474487  0.         -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  0.          1.22474487]]

Inverse transformed:
 [[  1. 200.   3.]
 [  4. 200.   6.]
 [  7. 200.   9.]]


In [52]:
class MyStandardScaler:
    def fit(self, X):
        X = np.asarray(X, dtype=float)
        self.mean_ = X.mean(axis=0)
        self.std_ = X.std(axis=0)
        self.std_[self.std_ == 0] = 1  # handle constant columns
        return self

    def transform(self, X):
        X = np.asarray(X, dtype=float)
        return (X - self.mean_) / self.std_

    def fit_transform(self, X):
        return self.fit(X).transform(X)

    def inverse_transform(self, X_scaled):
        X_scaled = np.asarray(X_scaled, dtype=float)
        return X_scaled * self.std_ + self.mean_


scaler = MyStandardScaler()
X_scaled = scaler.fit_transform(X)
print("Standardized:\n", X_scaled)

X_inv = scaler.inverse_transform(X_scaled)
print("\nInverse transformed:\n", X_inv)

Standardized:
 [[-1.22474487  0.         -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  0.          1.22474487]]

Inverse transformed:
 [[  1. 200.   3.]
 [  4. 200.   6.]
 [  7. 200.   9.]]
